name: NPM Publish

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print hello world
        run: echo "hello world"
      - name: Print the input name to STDOUT
        run: echo "The ${{ github.event_name }} type is ${{ github.event.action }} with tag ${{ github.event.tag }}"
