name: NPM Publish

on:
  release:
    types: [published, released]
  workflow_dispatch:

jobs:
  print-username:
    runs-on: ubuntu-latest


    steps:
      - name: Print hello world
        run: echo "hello world"
      - name: Print the input name to STDOUT
        run: echo "The ${{ github.event_name }} type is ${{ github.event.action }}. Pre-release is ${{ ! github.event.release.prerelease }}"
      - name: only print if pure pre-release
        run : echo "it is pure pre-release"
        if: github.event.action == 'published' && github.event.release.prerelease
      - name: only print if pure release
        run : echo "it is pure release or from pre-release to release"
        if: github.event.action == 'released'
